#!/bin/bash

stop_robot
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
echo $DIR
changed=0
cd $DIR
git remote update && git status -uno | grep -q 'Your branch is behind' && changed=1
if [ $changed = 1 ]; then
    git pull origin master
    echo "Updated successfully!"
    echo "Rebuilding Docker image..."
    $PWD/install.sh
else
    echo "Up-to-date"
fi
if [[ "$*" == *"--key"* ]]
then
    echo "Using key"
    touch $HOME/known_hosts
    KEYVOLUME="-v $HOME/iti0201_key:/root/.ssh/id_rsa -v $HOME/known_hosts:/root/.ssh/known_hosts"
fi
sudo docker run --privileged --rm -it --env "DISPLAY" $KEYVOLUME --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" --name iti0201 iti0201 robot_test "$@"
