#!/bin/bash

killall gzserver gzclient roscore -9 >/dev/null 2>&1

cd ~
DIRECTORY="iti0201-2018"

if [ "$#" -lt 3 ]; then
    echo "USAGE: robot_test [uni-id] [exercise_number] [map_number]"
    echo "You can also add optional arguments of -i=[ir_noise], -w=[wait_time], -x=[x] and -y=[y], -Y=[yaw], --cone, --noise, --realmotors, --realism, --blind"
    exit 0
fi

git_user_name=$1
exercise_number=$2
map_number=$3

ir_noise=0
waiting_time=12

yaw_start=0
cone=false
noise=0
realmotors=0
blind=0
debug=0

for i in "$@"
do
case $i in
    -i=*|--ir=*)
    ir_noise="${i#*=}"
    shift # past argument=value
    ;;
    -w=*|--wait=*)
    waiting_time="${i#*=}"
    shift # past argument=value
    ;;
    -x=*|--xstart=*)
    x_start="${i#*=}"
    shift # past argument=value
    ;;
    -y=*|--ystart=*)
    y_start="${i#*=}"
    shift # past argument=value
    ;;
    -Y=*|--yawstart=*)
    yaw_start="${i#*=}"
    shift # past argument=value
    ;;
    --cone)
    cone=true
    shift
    ;;
    --noise)
    noise=1
    shift
    ;;
    --realmotors)
    realmotors=1
    shift
    ;;
    --blind)
    blind=1
    shift
    ;;
    --debug)
    debug=1
    shift
    ;;
    --realism)
    cone=true
    realmotors=1
    noise=1
    blind=1
    echo "REALISM"
    shift
    ;;
    --default)
    DEFAULT=YES
    shift # past argument with no value
    ;;
    *)
          # unknown option
    ;;
esac
done

git_address="https://$git_user_name@gitlab.cs.ttu.ee/$git_user_name/$DIRECTORY.git"

echo $git_address

# rm -rf $DIRECTORY # Temporary hack for when the iti0201 repo already exists, will be fixed soon

if [ -d "$DIRECTORY" ]; then
    echo "Repository already exists. Updating.."
    cd $DIRECTORY
    git pull
else
    echo "Repository doesn't exist yet. Creating one now..."
    git clone $git_address
    cd $DIRECTORY
fi

exercise_name=""
directory_name=""

if [ -d "$exercise_number" ]; then
    cd $exercise_number
else
    echo "Your files do not contain the $exercise_number folder."
    exit 1
fi

if ! [ -f "robot.py" ]; then
    echo "Your directory $exercise_number folder does not contain the necessary robot.py file."
    exit 1
fi

if [[ -z "$x_start" || -z "$y_start" ]]; then
    echo "x and y not set"
    if $cone; then
        map_number_cone=""$map_number"_cone"
        map_name_cone="$map_number_cone.world"
        map_name="$map_number.world"
        map_number+="_cone"
        copy_path=~/catkin_ws/src/pibot_gazebo/worlds/$exercise_number/$map_name_cone
        touch "$copy_path"
        cp ~/catkin_ws/src/pibot_gazebo/worlds/$exercise_number/$map_name "$copy_path"
        uri="_cone"
        sed -i "s|\(<uri>model://iti0201_robot\)[^<>]*\(</uri>\)|\1${uri}\2|" $copy_path
        sed -i "s|\(<name>iti0201_robot\)[^<>]*\(</name>\)|\1${uri}\2|" $copy_path
        echo "IR Sensors with cone"
    fi
else
    map_number+="_custom"
fi

echo "IR noise: $noise"
echo "Real motors: $realmotors"
echo "Blind: $blind"
echo "Debug: $debug"
x-terminal-emulator -e roslaunch pibot_gazebo default.launch dir:=$exercise_number map:=$map_number noise:=$noise realmotors:=$realmotors blind:=$blind debug:=$debug

if [[ -z "$x_start" || -z "$y_start" ]]; then
    echo "spawning model at default location"
else
    echo "spawning model at specified location"
    x-terminal-emulator -e rosrun gazebo_ros spawn_model -file `rospack find pibot_description`/models/iti0201_robot/urdf/pibot.urdf -urdf -x "$x_start" -y "$y_start" -z 0 -Y "$yaw_start" -model pibot
fi

x-terminal-emulator -e script_launch ~/$DIRECTORY/$exercise_number $waiting_time

#roslaunch lego_gazebo lego_$exercise_name.launch
