#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "Illegal number of parameters"
    exit
fi

echo ".."
echo ".."
echo ".."
echo $1
sleep $2s # waiting time to get ready; 

cd $1 

python3 "robot.py"

$SHELL
