#!/bin/bash

echo "Updating files..."
cd ~/catkin_ws
echo "Removing old repos..."
rm -rf src
echo "Cloning repos..."
git clone https://github.com/iti0201/simulation src
cd src
echo "Initializing workspace..."
catkin_init_workspace
cd ..
echo "Compiling workspace..."
catkin_make
echo "Sourcing setup..."
. devel/setup.bash
echo "Done! Enjoy!"
